### ISSUE TITLE
Nice job on README.md

### ISSUE THREAD

**Issue by nicksuch** [nickveil/nickveil.github.io#3]
This looks good @nickveil ! No suggestions to fix here, just wanted you to have a sample "GitHub Issue" to resolve.

**Comment by nickveil** [comment]
Cool thanks. Is it ok for me to mess around with this repository a little more or will we build upon it later in the course?

**Comment by nicksuch** [comment]
@nickveil For Prework Week 2, you'll be adding some HTML and CSS files to this repository, so feel free to get started on those! For any other exploration and experiments, I'd recommend creating a new repository. GitHub gives you as many free public repos as you'd like, so create away!
